[package]
name = "tycho-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
logos = "0.15.0"
mimalloc = { version = "*", default-features = false }
rustc-hash = "2.1.0"
structopt = "0.3.26"
thiserror = "2.0.11"
