[package]
name = "tycho-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
logos = "0.13.0"
mimalloc = { version = "*", default-features = false }
rustc-hash = "1.1.0"
structopt = "0.3.26"
thiserror = "1.0.43"
